name: PDI Global Superstore Autograding

on:
  push:
    paths:
      - "Global_Superstore_Transformation.ktr"
      - "output.csv"
      - "pdi_result.png"
      - "tests/**"
      - ".github/workflows/pdi-autograding.yml"

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x tests/test.sh

      - name: Run autograder
        run: ./tests/test.sh
