name: PDI Global Superstore Autograding

on:
  push:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Autograder
        run: |
          chmod +x tests/test.sh
          ./tests/test.sh
